// Code generated by internal/claw3d/sha-stamp. DO NOT EDIT.
package claw3d

// BundleSHA256Generated is the deterministic content hash of every file
// under internal/claw3d/bundle/, stamped by the sha-stamp tool during
// release builds. Reported via pan-agent doctor and /office/config.js so
// clients can detect which exact bundle they are talking to.
//
// The non-generated BundleSHA256 constant in embed.go holds the
// development placeholder; release builds override it via ldflags:
//
//	go build -ldflags "-X .../claw3d.BundleSHA256=5774fab2be7d82b066b3b1a90a71752eace457aa0bc3ac5c02e225c78fb6616f" ...
const BundleSHA256Generated = "5774fab2be7d82b066b3b1a90a71752eace457aa0bc3ac5c02e225c78fb6616f"
const BundleFileCount = 144
