// Command sha-stamp computes the SHA256 of the embedded Claw3D bundle and
// writes it into bundle_sha.go as a constant that the adapter reports via
// pan-agent doctor and /office/config.js.
//
// Invoked as:
//
//	go generate ./internal/claw3d/...
//
// which runs the //go:generate directive in bundle_sha_gen.go. The output
// overwrites internal/claw3d/bundle_sha.go — do not hand-edit that file.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	// Walk up from CWD until we find go.mod so paths work whether invoked
	// directly from repo root OR via `go generate` (which runs the tool with
	// CWD set to the package dir containing the directive).
	root, err := findRepoRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "sha-stamp: locate repo root:", err)
		os.Exit(1)
	}
	bundleDir := filepath.Join(root, "internal", "claw3d", "bundle")
	outFile := filepath.Join(root, "internal", "claw3d", "bundle_sha.go")

	// Walk the bundle tree in deterministic order so the checksum is
	// stable across filesystems with different directory-entry orderings.
	var files []string
	err = filepath.WalkDir(bundleDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "sha-stamp: walk:", err)
		os.Exit(1)
	}
	sort.Strings(files)

	h := sha256.New()
	for _, f := range files {
		rel, _ := filepath.Rel(bundleDir, f)
		rel = strings.ReplaceAll(rel, "\\", "/")
		fmt.Fprintf(h, "%s\x00", rel)
		in, err := os.Open(f)
		if err != nil {
			fmt.Fprintln(os.Stderr, "sha-stamp: open:", err)
			os.Exit(1)
		}
		if _, err := io.Copy(h, in); err != nil {
			in.Close()
			fmt.Fprintln(os.Stderr, "sha-stamp: read:", err)
			os.Exit(1)
		}
		in.Close()
		fmt.Fprintf(h, "\x00")
	}
	sum := hex.EncodeToString(h.Sum(nil))

	out := fmt.Sprintf(`// Code generated by internal/claw3d/sha-stamp. DO NOT EDIT.
package claw3d

// BundleSHA256Generated is the deterministic content hash of every file
// under internal/claw3d/bundle/, stamped by the sha-stamp tool during
// release builds. Reported via pan-agent doctor and /office/config.js so
// clients can detect which exact bundle they are talking to.
//
// The non-generated BundleSHA256 constant in embed.go holds the
// development placeholder; release builds override it via ldflags:
//
//	go build -ldflags "-X .../claw3d.BundleSHA256=%s" ...
const BundleSHA256Generated = %q
const BundleFileCount = %d
`, sum, sum, len(files))

	if err := os.WriteFile(outFile, []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "sha-stamp: write:", err)
		os.Exit(1)
	}
	fmt.Printf("sha-stamp: %d files, sha256=%s\n", len(files), sum[:12])
}

func findRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := cwd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found above %s", cwd)
		}
		dir = parent
	}
}
